;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        cua--prefix-override-handler
        cua-cut-region
        cua-paste
        delete-horizontal-space
        dired-clean-directory
        electric-pair-delete-pair
        emmet-expand-line
        eval-print-last-sexp
        forward-to-word-begin
        org-return-indent
        org-self-insert-command
        python-indent-dedent-line
        sp-backward-delete-char
        sp-backward-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        ))
