;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-to-word-end
        c-electric-brace
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        crux-move-beginning-of-line
        cua--prefix-override-handler
        cua-copy-region
        cua-cut-region
        cua-paste
        delete-horizontal-space
        dired-clean-directory
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        emmet-expand-line
        eval-print-last-sexp
        forward-to-word-begin
        helm-M-x
        helm-show-kill-ring
        ignore
        indent-for-tab-command
        kill-region
        org-cycle
        org-delete-char
        org-end-of-line
        org-kill-line
        org-metaright
        org-return-indent
        org-self-insert-command
        org-yank
        python-indent-dedent-line
        sp-backward-delete-char
        sp-backward-kill-word
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        zop-up-to-char
        ))
